# Site Settings
title:         Distilled Archives
permalink:     /:title/
paginate_path: /page:num
timezone:      null

# Handling Reading
safe:         false
keep_files:   [".git"]

# Conversion
markdown:     kramdown
markdown_ext: "txt"
encoding:     "utf-8"
